"""PCG (Plan Comptable Général) — comptes principaux pour Maître Comptable.

Source : règlement ANC 2014-03 version consolidée 1er janvier 2026
Réforme ANC 2022-06 intégrée (suppression transferts charges, plan ~1600 comptes).

Phase 1 Mode B : ~200 comptes les plus utilisés en BC1 (saisie courante,
factures, TVA mécanisme). Phase 2 : extraction PCG complet PDF si besoin.

CLASSES :
- 1 : Comptes de capitaux (capitaux propres, emprunts)
- 2 : Comptes d'immobilisations
- 3 : Comptes de stocks et en-cours
- 4 : Comptes de tiers
- 5 : Comptes financiers
- 6 : Comptes de charges
- 7 : Comptes de produits
"""
from __future__ import annotations

# Comptes principaux PCG (numéro → libellé). Sous-comptes les plus courants en BC1.
PCG_MAIN_ACCOUNTS: dict[str, str] = {
    # ── Classe 1 — Capitaux ──────────────────────────────────────
    "10": "Capital et réserves",
    "101": "Capital",
    "1011": "Capital souscrit - non appelé",
    "1012": "Capital souscrit - appelé, non versé",
    "1013": "Capital souscrit - appelé, versé",
    "104": "Primes liées au capital social",
    "106": "Réserves",
    "1061": "Réserve légale",
    "1063": "Réserves statutaires ou contractuelles",
    "1068": "Autres réserves",
    "11": "Report à nouveau",
    "110": "Report à nouveau (solde créditeur)",
    "119": "Report à nouveau (solde débiteur)",
    "12": "Résultat de l'exercice",
    "120": "Résultat de l'exercice (bénéfice)",
    "129": "Résultat de l'exercice (perte)",
    "13": "Subventions d'investissement",
    "14": "Provisions réglementées",
    "145": "Amortissements dérogatoires",
    "15": "Provisions",
    "151": "Provisions pour risques",
    "1511": "Provisions pour litiges",
    "1512": "Provisions pour garanties données aux clients",
    "157": "Provisions pour charges à répartir",
    "16": "Emprunts et dettes assimilées",
    "164": "Emprunts auprès des établissements de crédit",
    "1675": "Emprunts et dettes assortis de conditions particulières",
    "168": "Autres emprunts et dettes assimilées",

    # ── Classe 2 — Immobilisations ───────────────────────────────
    "20": "Immobilisations incorporelles",
    "201": "Frais d'établissement",
    "203": "Frais de recherche et de développement",
    "205": "Concessions, brevets, licences, marques, procédés",
    "206": "Droit au bail",
    "207": "Fonds commercial",
    "208": "Autres immobilisations incorporelles",
    "21": "Immobilisations corporelles",
    "211": "Terrains",
    "213": "Constructions",
    "215": "Installations techniques, matériel et outillage industriels",
    "2154": "Matériel industriel",
    "2155": "Outillage industriel",
    "218": "Autres immobilisations corporelles",
    "2181": "Installations générales, agencements, aménagements",
    "2182": "Matériel de transport",
    "2183": "Matériel de bureau et matériel informatique",
    "2184": "Mobilier",
    "23": "Immobilisations en cours",
    "26": "Participations et créances rattachées à des participations",
    "261": "Titres de participation",
    "27": "Autres immobilisations financières",
    "271": "Titres immobilisés autres que TIAP",
    "274": "Prêts",
    "275": "Dépôts et cautionnements versés",
    "28": "Amortissements des immobilisations",
    "2801": "Amortissements des frais d'établissement",
    "2805": "Amortissements des concessions, brevets...",
    "2811": "Amortissements des terrains de gisement",
    "2813": "Amortissements des constructions",
    "2815": "Amortissements des installations techniques",
    "2818": "Amortissements des autres immobilisations corporelles",
    "29": "Dépréciations des immobilisations",

    # ── Classe 3 — Stocks et en-cours ────────────────────────────
    "30": "(Compte non utilisé en France)",
    "31": "Matières premières (et fournitures)",
    "32": "Autres approvisionnements",
    "33": "En-cours de production de biens",
    "34": "En-cours de production de services",
    "35": "Stocks de produits",
    "355": "Produits finis",
    "37": "Stocks de marchandises",
    "39": "Dépréciations des stocks et en-cours",

    # ── Classe 4 — Comptes de tiers ──────────────────────────────
    "40": "Fournisseurs et comptes rattachés",
    "401": "Fournisseurs",
    "4011": "Fournisseurs - Achats de biens et prestations de services",
    "4017": "Fournisseurs - Retenues de garantie",
    "403": "Fournisseurs - Effets à payer",
    "404": "Fournisseurs d'immobilisations",
    "408": "Fournisseurs - Factures non parvenues",
    "409": "Fournisseurs débiteurs",
    "4091": "Fournisseurs - Avances et acomptes versés sur commandes",
    "41": "Clients et comptes rattachés",
    "411": "Clients",
    "4111": "Clients - Ventes de biens ou de prestations de services",
    "413": "Clients - Effets à recevoir",
    "416": "Clients douteux ou litigieux",
    "418": "Clients - Produits non encore facturés",
    "419": "Clients créditeurs",
    "4191": "Clients - Avances et acomptes reçus sur commandes",
    "42": "Personnel et comptes rattachés",
    "421": "Personnel - Rémunérations dues",
    "425": "Personnel - Avances et acomptes",
    "427": "Personnel - Oppositions",
    "428": "Personnel - Charges à payer et produits à recevoir",
    "43": "Sécurité sociale et autres organismes sociaux",
    "431": "Sécurité sociale",
    "437": "Autres organismes sociaux",
    "438": "Organismes sociaux - Charges à payer et produits à recevoir",
    "44": "État et autres collectivités publiques",
    "442": "État - Impôts et taxes recouvrables sur des tiers",
    "444": "État - Impôts sur les bénéfices",
    "445": "État - Taxes sur le chiffre d'affaires",
    "4452": "TVA due intracommunautaire",
    "44551": "TVA à décaisser",
    "44552": "TVA à décaisser - Coefficient de déduction",
    "4456": "Taxes sur le chiffre d'affaires déductibles",
    "44562": "TVA déductible sur immobilisations",
    "44566": "TVA déductible sur autres biens et services",
    "44567": "Crédit de TVA à reporter",
    "4457": "Taxes sur le chiffre d'affaires collectées par l'entreprise",
    "44571": "TVA collectée",
    "4458": "Taxes sur le chiffre d'affaires à régulariser ou en attente",
    "44583": "Remboursement de taxes sur le chiffre d'affaires demandé",
    "447": "Autres impôts, taxes et versements assimilés",
    "45": "Groupe et associés",
    "455": "Associés - Comptes courants",
    "46": "Débiteurs divers et créditeurs divers",
    "467": "Autres comptes débiteurs ou créditeurs",
    "47": "Comptes transitoires ou d'attente",
    "471": "Comptes d'attente",
    "48": "Comptes de régularisation",
    "486": "Charges constatées d'avance",
    "487": "Produits constatés d'avance",
    "49": "Dépréciations des comptes de tiers",
    "491": "Dépréciations des comptes de clients",

    # ── Classe 5 — Comptes financiers ────────────────────────────
    "50": "Valeurs mobilières de placement",
    "503": "Actions",
    "506": "Obligations",
    "51": "Banques, établissements financiers et assimilés",
    "511": "Valeurs à l'encaissement",
    "5112": "Chèques à encaisser",
    "512": "Banques",
    "5121": "Comptes en monnaie nationale",
    "514": "Chèques postaux",
    "53": "Caisse",
    "530": "Caisse",
    "54": "Régies d'avances et accréditifs",
    "58": "Virements internes",
    "59": "Dépréciations des comptes financiers",

    # ── Classe 6 — Charges ───────────────────────────────────────
    "60": "Achats (sauf 603)",
    "601": "Achats stockés - Matières premières (et fournitures)",
    "602": "Achats stockés - Autres approvisionnements",
    "603": "Variations des stocks",
    "604": "Achats d'études et prestations de services",
    "605": "Achats de matériel, équipements et travaux",
    "606": "Achats non stockés de matières et fournitures",
    "6061": "Fournitures non stockables (eau, énergie...)",
    "60611": "Eau",
    "60612": "Électricité",
    "60613": "Chauffage",
    "6063": "Fournitures d'entretien et de petit équipement",
    "6064": "Fournitures administratives",
    "6067": "Fournitures et matériel d'enseignement et de recherche",
    "607": "Achats de marchandises",
    "608": "(Compte réservé, le cas échéant, à la récapitulation des frais accessoires d'achat)",
    "609": "Rabais, remises et ristournes obtenus sur achats",
    "61": "Services extérieurs",
    "611": "Sous-traitance générale",
    "612": "Redevances de crédit-bail",
    "613": "Locations",
    "614": "Charges locatives et de copropriété",
    "615": "Entretien et réparations",
    "616": "Primes d'assurances",
    "617": "Études et recherches",
    "618": "Divers (documentation générale, séminaires, colloques)",
    "619": "Rabais, remises et ristournes obtenus sur services extérieurs",
    "62": "Autres services extérieurs",
    "621": "Personnel extérieur à l'entreprise",
    "622": "Rémunérations d'intermédiaires et honoraires",
    "623": "Publicité, publications, relations publiques",
    "624": "Transports de biens et transports collectifs du personnel",
    "625": "Déplacements, missions et réceptions",
    "626": "Frais postaux et frais de télécommunications",
    "627": "Services bancaires et assimilés",
    "628": "Divers (concours divers, cotisations, etc.)",
    "63": "Impôts, taxes et versements assimilés",
    "631": "Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)",
    "633": "Impôts, taxes et versements assimilés sur rémunérations (autres organismes)",
    "635": "Autres impôts, taxes et versements assimilés (administrations des impôts)",
    "637": "Autres impôts, taxes et versements assimilés (autres organismes)",
    "64": "Charges de personnel",
    "641": "Rémunérations du personnel",
    "6411": "Salaires, appointements",
    "6412": "Congés payés",
    "6413": "Primes et gratifications",
    "6414": "Indemnités et avantages divers",
    "645": "Charges de sécurité sociale et de prévoyance",
    "6451": "Cotisations à l'URSSAF",
    "6452": "Cotisations aux mutuelles",
    "6453": "Cotisations aux caisses de retraite",
    "646": "Cotisations sociales personnelles de l'exploitant",
    "647": "Autres charges sociales",
    "648": "Autres charges de personnel",
    "65": "Autres charges de gestion courante",
    "651": "Redevances pour concessions, brevets, licences, marques, procédés...",
    "654": "Pertes sur créances irrécouvrables",
    "658": "Charges diverses de gestion courante",
    "66": "Charges financières",
    "661": "Charges d'intérêts",
    "6611": "Intérêts des emprunts et dettes",
    "664": "Pertes sur créances liées à des participations",
    "665": "Escomptes accordés",
    "666": "Pertes de change",
    "667": "Charges nettes sur cessions de valeurs mobilières de placement",
    "668": "Autres charges financières",
    "67": "Charges exceptionnelles",
    "671": "Charges exceptionnelles sur opérations de gestion",
    "675": "Valeurs comptables des éléments d'actif cédés",
    "678": "Autres charges exceptionnelles",
    "68": "Dotations aux amortissements, dépréciations et provisions",
    "681": "Dotations aux amortissements, dépréciations et provisions - Charges d'exploitation",
    "6811": "Dotations aux amortissements sur immobilisations incorporelles et corporelles",
    "6815": "Dotations aux provisions pour risques et charges d'exploitation",
    "6816": "Dotations aux dépréciations des immobilisations incorporelles et corporelles",
    "6817": "Dotations aux dépréciations des actifs circulants",
    "686": "Dotations aux amortissements, dépréciations et provisions - Charges financières",
    "687": "Dotations aux amortissements, dépréciations et provisions - Charges exceptionnelles",
    "69": "Participation des salariés - Impôts sur les bénéfices et assimilés",
    "691": "Participation des salariés aux résultats",
    "695": "Impôts sur les bénéfices",
    "697": "Imposition forfaitaire annuelle des sociétés",
    "699": "Produits - Reports en arrière des déficits",

    # ── Classe 7 — Produits ──────────────────────────────────────
    "70": "Ventes de produits fabriqués, prestations de services, marchandises",
    "701": "Ventes de produits finis",
    "702": "Ventes de produits intermédiaires",
    "703": "Ventes de produits résiduels",
    "704": "Travaux",
    "705": "Études",
    "706": "Prestations de services",
    "707": "Ventes de marchandises",
    "708": "Produits des activités annexes",
    "709": "Rabais, remises et ristournes accordés par l'entreprise",
    "71": "Production stockée (ou déstockage)",
    "713": "Variation des stocks (en-cours de production, produits)",
    "72": "Production immobilisée",
    "74": "Subventions d'exploitation",
    "75": "Autres produits de gestion courante",
    "751": "Redevances pour concessions, brevets...",
    "754": "Ristournes perçues des coopératives",
    "758": "Produits divers de gestion courante",
    "76": "Produits financiers",
    "761": "Produits de participations",
    "762": "Produits des autres immobilisations financières",
    "763": "Revenus des autres créances",
    "764": "Revenus des valeurs mobilières de placement",
    "765": "Escomptes obtenus",
    "766": "Gains de change",
    "767": "Produits nets sur cessions de valeurs mobilières de placement",
    "768": "Autres produits financiers",
    "77": "Produits exceptionnels",
    "771": "Produits exceptionnels sur opérations de gestion",
    "775": "Produits des cessions d'éléments d'actif",
    "778": "Autres produits exceptionnels",
    "78": "Reprises sur amortissements, dépréciations et provisions",
    "781": "Reprises sur amortissements, dépréciations et provisions - Produits d'exploitation",
    "786": "Reprises sur amortissements, dépréciations et provisions - Produits financiers",
    "787": "Reprises sur amortissements, dépréciations et provisions - Produits exceptionnels",
    "79": "Transferts de charges (NB : supprimé par réforme ANC 2022-06 — comptes 791-795 abrogés)",
}


# Classes PCG : libellés
PCG_CLASSES: dict[str, str] = {
    "1": "Comptes de capitaux (capitaux propres, autres fonds propres, emprunts et dettes assimilées)",
    "2": "Comptes d'immobilisations",
    "3": "Comptes de stocks et en-cours",
    "4": "Comptes de tiers",
    "5": "Comptes financiers",
    "6": "Comptes de charges",
    "7": "Comptes de produits",
    "8": "Comptes spéciaux",
    "9": "Comptes analytiques",
}


# Taux TVA français standard 2026
TVA_TAUX_STANDARD: list[float] = [0.0, 2.1, 5.5, 10.0, 20.0]
TVA_TAUX_DEFAULT_NORMAL = 20.0
TVA_TAUX_INTERMEDIAIRE = 10.0
TVA_TAUX_REDUIT = 5.5
TVA_TAUX_PARTICULIER = 2.1
