#!/bin/bash
# S59 — Persistent recreate of dify-api + dify-worker with INNER_API env vars.
#
# CONTEXT
# Dify deployed via 'docker run' (no compose label). R1 hot-patch
# `/app/api/configs/feature/__init__.py` survives 'docker restart' but is
# lost on 'docker rm + run' rebuild. This script recreates the containers
# WITH the 2 missing env vars baked in, so the fix persists across rebuilds.
#
# WHAT IT DOES
# Reads current env from the running dify-api / dify-worker (docker inspect)
# to preserve all existing secrets + config, then appends/overrides :
#   INNER_API=true                       (enables /inner/api/* blueprint)
#   INNER_API_KEY_FOR_PLUGIN=<inner key> (matches daemon DIFY_INNER_API_KEY)
#
# The inner key is read from the running dify-plugin-daemon's
# DIFY_INNER_API_KEY env var. No plaintext secrets in this script.
#
# WHEN TO USE
# - After cosmos rebuild / restore that recreated dify containers
# - After Dify version upgrade
# - When auditing INNER_API config drift via smoke-test --deep alert
#
# Successor to /tmp/recreate_dify-api.sh + /tmp/recreate_dify-worker.sh
# (those /tmp scripts can be re-generated by this one if lost).
set -e

# Read inner key from the live plugin daemon (avoids hardcoding)
INNER_KEY=$(docker exec dify-plugin-daemon env 2>/dev/null | grep '^DIFY_INNER_API_KEY=' | cut -d= -f2-)
if [ -z "$INNER_KEY" ]; then
    echo "❌ Cannot read DIFY_INNER_API_KEY from dify-plugin-daemon container." >&2
    echo "   Either daemon is not running, or env var not set. Aborting." >&2
    exit 1
fi
echo "Inner key fingerprint: ${INNER_KEY:0:12}... (read from dify-plugin-daemon)"

recreate() {
    local name=$1   # dify-api or dify-worker
    if ! docker inspect "$name" >/dev/null 2>&1; then
        echo "❌ $name not running — cannot snapshot env. Provide deploy from .env file instead." >&2
        return 1
    fi

    # Snapshot current container config: image, network, ports, mounts, env
    local image network restart
    image=$(docker inspect "$name" --format '{{.Config.Image}}')
    network=$(docker inspect "$name" --format '{{range $k,$_ := .NetworkSettings.Networks}}{{$k}}{{end}}' | head -1)
    restart=$(docker inspect "$name" --format '{{.HostConfig.RestartPolicy.Name}}')

    # Build -e args from current env, EXCLUDING the 2 we'll override + system PATH/PYTHON noise
    local env_args=()
    while IFS= read -r line; do
        case "$line" in
            INNER_API=*|INNER_API_KEY_FOR_PLUGIN=*) continue ;;  # skip — we'll re-add
            "") continue ;;
        esac
        env_args+=(-e "$line")
    done < <(docker inspect "$name" --format '{{range .Config.Env}}{{.}}{{println}}{{end}}')

    # Build -p args from current port bindings (only dify-api binds a port)
    local port_args=()
    if [ "$name" = "dify-api" ]; then
        port_args+=(-p "127.0.0.1:5001:5001")
    fi

    # Build -v args from current bind mounts
    local mount_args=()
    while IFS= read -r m; do
        [ -n "$m" ] && mount_args+=(-v "$m")
    done < <(docker inspect "$name" --format '{{range .Mounts}}{{.Source}}:{{.Destination}}{{if eq .Mode "ro"}}:ro{{end}}{{println}}{{end}}')

    echo "Recreating $name (image=$image, network=$network, restart=$restart)..."
    docker stop "$name" 2>/dev/null || true
    docker rm "$name" 2>/dev/null || true
    docker run -d --name "$name" --restart "$restart" --network "$network" \
        "${mount_args[@]}" \
        "${port_args[@]}" \
        "${env_args[@]}" \
        -e INNER_API=true \
        -e "INNER_API_KEY_FOR_PLUGIN=$INNER_KEY" \
        "$image"
    echo "✅ $name recreated"
}

recreate dify-api
recreate dify-worker

# Wait healthy
echo
for i in 1 2 3 4 5 6 7 8 9 10; do
    sleep 3
    status=$(docker exec dify-api curl -s -o /dev/null -w "%{http_code}" http://localhost:5001/health 2>/dev/null)
    echo "  iter $i dify-api health=$status"
    if [ "$status" = "200" ]; then break; fi
done

echo
echo "Verification:"
docker exec dify-api python3 -c "from configs import dify_config; print('  INNER_API:', dify_config.INNER_API); print('  INNER_API_KEY_FOR_PLUGIN[:12]:', dify_config.INNER_API_KEY_FOR_PLUGIN[:12], '...')"
